# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh cluster key secret

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}-cluster-key
data:
  key: # string base64 encoded
