version: "3.7"
services:
    zookeeper:
        restart: always
        hostname: zookeeper
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        networks:
            palantir-backend:
                ipv4_address: 10.1.1.5
    
    kafka:
        restart: always
        image: wurstmeister/kafka
        hostname: kafka
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        networks:
            palantir-backend:
                ipv4_address: 10.1.1.6
        depends_on:
        - zookeeper
    
    attacker:
        restart: always
        build: attacker
        hostname: attacker
        stdin_open: true
        tty: true
        networks:
            palantir-backend:
                ipv4_address: 10.1.1.100
        depends_on: 
            - secaas_snort
        command: bash
        privileged: true

    secaas_snort:
        restart: always
        build: snort2
        hostname: snort2
        stdin_open: true
        tty: true
        networks: 
            # eth0
            palantir-ids:
                ipv4_address: 10.2.1.7
            # eth 1
            palantir-backend:
                ipv4_address: 10.1.1.7
        command: "bash"
        depends_on:
        - kafka
        volumes:
            - "./snort2/portscanning.rules:/etc/snort/rules/local.rules"
       
    sme-db:
        restart: always
        build: sme-db
        command: ['mysqld','--character-set-server=utf8mb4']
        environment:
            MYSQL_ROOT_PASSWORD: root
        
        hostname: sme-db
        depends_on:
        - secaas_snort
        stdin_open: true
        tty: true
        networks: 
            palantir-backend:
                ipv4_address: 10.1.1.8
            palantir-ids:
                ipv4_address: 10.2.1.8

    sme-openemr:
        restart: always
        build: sme-openemr
        ports:
        - "80:80"
        - "443:443"
        environment:
            MYSQL_HOST: 10.1.1.8
            MYSQL_ROOT_PASS: root
            MYSQL_USER: openemr
            MYSQL_PASS: openemr
            OE_USER: openemr
            OE_PASS: openemr
        depends_on:
        - sme-db
        - secaas_snort
        hostname: sme-openemr
        stdin_open: true
        tty: true
        networks: 
            palantir-backend:
                ipv4_address: 10.1.1.10
            palantir-ids:
                ipv4_address: 10.2.1.10
        privileged: true
        command: ['/bin/sh']

networks:
    palantir-backend:
        internal: true
        name: br1-palantir-internal
        ipam:
            config:
                - subnet: "10.1.1.0/24"
    palantir-ids:
        internal: true
        name: br2-palantir-ids
        ipam:
            config:
                - subnet: "10.2.1.0/24"
